version: '3.9'
services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  api:
    build: ../apps/api
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/ecotracker
      - JWT_SECRET=change-me
    depends_on:
      - mongo
    ports:
      - '4000:4000'
  ml:
    build: ../apps/ml
    ports:
      - '8000:8000'
volumes:
  mongo-data:

